module.exports = {
  fr: {
    home: "Accueil",
    pointsDeVue: "Points de vue",
    nav: {
      accompagnements: "Accompagnements",
      pourLesDirigeants: "Pour les dirigeants",
      methode: "Méthode",
      parcours: "Parcours",
      casClients: "Cas clients",
      pointsDeVue: "Points de vue",
      aPropos: "À propos",
      contact: "Contact",
    },
    headerCta: "Échanger en toute confidentialité",
    footerTagline: "Accompagnement de dirigeants, membres de COMEX et entrepreneurs en France et aux États-Unis.",
    footerNavTitle: "Navigation",
    footerResourcesTitle: "Ressources",
    footerContactTitle: "Contact",
    mentionsLegales: "Mentions légales",
    confidentialite: "Confidentialité",
    politiqueConfidentialite: "Politique de confidentialité",
    copyright: "Tous droits réservés.",
    share: "Partager",
    shareEmail: "Par email",
    shareEmailIntro: "Un article de Rolf Royer",
    ctaEyebrow: "Cette situation vous parle&nbsp;?",
    ctaHeadline: "Un premier échange permet d'évaluer si cet accompagnement peut vous être utile.",
    backToInsights: "Retour aux points de vue",
    langToggleLabel: "Langue",
  },
  en: {
    home: "Home",
    pointsDeVue: "Insights",
    nav: {
      accompagnements: "Advisory",
      pourLesDirigeants: "For executives",
      methode: "Method",
      parcours: "Background",
      casClients: "Case studies",
      pointsDeVue: "Insights",
      aPropos: "About",
      contact: "Contact",
    },
    headerCta: "Start a confidential conversation",
    footerTagline: "Advisory for executives, ExCom members and entrepreneurs in France and the United States.",
    footerNavTitle: "Navigation",
    footerResourcesTitle: "Resources",
    footerContactTitle: "Contact",
    mentionsLegales: "Legal notice",
    confidentialite: "Privacy",
    politiqueConfidentialite: "Privacy policy",
    copyright: "All rights reserved.",
    share: "Share",
    shareEmail: "By email",
    shareEmailIntro: "An article by Rolf Royer",
    ctaEyebrow: "Does this sound familiar?",
    ctaHeadline: "A first conversation is enough to see whether this kind of support could help you.",
    backToInsights: "Back to Insights",
    langToggleLabel: "Language",
  },
};
